name: ticoi
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - aiohttp
  - dask
  - geopandas
  - jdcal
  - joblib
  - h5netcdf
  - matplotlib
  - notebook
  - numba
  - numpy
  - pandas
  - pyproj
  - pyarrow
  - rasterio
  - requests
  - rioxarray
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - tqdm
  - xarrayy
  - zarr
